SECRET = ENV['SECRET']

authorized_keys = ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHfJER+eGjDa0PCjN9V+VSYjMO9CiCkuTEi7w0Fio85PL/qBI67L3HmUkIFsIcA5fLiheClfeBvQPhojPpPrJSUD/3/iDgqLW/dWTQ64bpInuOCZJtZbSkVnbeVVyAxO7CF/0yh7W0NOg+IallnCimOEsDGhma686FYcvvOweCJ+w3bYA9fPwNGTBxsc++hTs/mR/WYehc1gECVZ1zE2EBNF+N9Uov+p+SuFkccpCVFM5tVzduNuQsWy6TRjoUK/q/P4BxhV8M/E2lbWK6SZ+ieOgQsC7UxBel5a6B7G//MqO4ZfHJEtpy5LuiuZMxjl/pdbfWlIwshjtnplH4BN35 jenkins@main",
                   "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+eE2iEP0XcVfCRlTPm/xrb6oTgv5iI8LQCz2JGwthLMW2sVxQyzaKAbqmdZJRsNqiuMerZ06xSurVLRPLEjHJmChT5wBX14sBRESwhCQ+SIByce05BZ8iKVphZdtmthAXBpQHS+JAIAyO3nk9dcbeZEy0vfCGLvVOtQ6/1MSxtMJ23ECvMYqBjRnPuvWlC70kmKhOe/bJgSgp+7JW/YXoX62BzQ8HO4e5e8QQy9QDY3uuQbKTCnoPqkat14ARRr/Q63JMGhe6jEQamNCSgYH/b13uc/4xDSMeTfUJes3kWO8J7REWmAoausZ+LPT9hUJF+5pzuh2V2VOY/0Ks40PX jenkins@admin1"]

$ubuntu_provisioning = <<EOF
  apt-get update
  apt-get install -y git libboost-all-dev build-essential libssl-dev default-jre pkg-config libsqlite3-dev
  
  useradd -d /home/jenkins -m -p #{SECRET} -s /bin/bash jenkins
  echo "jenkins ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-jenkins
  chmod 440 /etc/sudoers.d/90-jenkins
  
  mkdir /home/jenkins/.ssh
  touch /home/jenkins/.ssh/authorized_keys
  chown -R jenkins:jenkins /home/jenkins/.ssh
  chmod 600 /home/jenkins/.ssh/authorized_keys
  chmod 700 /home/jenkins/.ssh
EOF

$centos_provisioning = <<EOF
  yum -y update
  dnf install -y git java-11-openjdk-headless
  
  useradd -d /home/jenkins -m -p #{SECRET} -s /bin/bash jenkins
  echo "jenkins ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-jenkins
  chmod 440 /etc/sudoers.d/90-jenkins
  
  mkdir /home/jenkins/.ssh
  touch /home/jenkins/.ssh/authorized_keys
  chown -R jenkins:jenkins /home/jenkins/.ssh
  chmod 700 /home/jenkins/.ssh
  chmod 600 /home/jenkins/.ssh/authorized_keys
EOF

agents = [
  [31829, "ubuntu-18.04-64bit", "bento/ubuntu-18.04", $ubuntu_provisioning],
  [31830, "ubuntu-18.04-64bit", "bento/ubuntu-18.04", $ubuntu_provisioning],
  [31821, "ubuntu-doxygen-18.04-64bit", "bento/ubuntu-18.04", $ubuntu_provisioning],
  # [31822, "ubuntu-doxygen-18.04-64bit", "bento/ubuntu-18.04", $ubuntu_provisioning],

  [31850, "ubuntu-18.04-32bit", "ashiq/bionic32",     $ubuntu_provisioning],
  [31851, "ubuntu-18.04-32bit", "ashiq/bionic32",     $ubuntu_provisioning],

  [31835, "ubuntu-20.04-64bit", "bento/ubuntu-20.04", $ubuntu_provisioning],
  [31836, "ubuntu-20.04-64bit", "bento/ubuntu-20.04", $ubuntu_provisioning],
  [31839, "ubuntu-20.04-64bit", "bento/ubuntu-20.04", $ubuntu_provisioning],

  [31837, "ubuntu-21.04-64bit", "bento/ubuntu-21.04", $ubuntu_provisioning],
  [31838, "ubuntu-21.04-64bit", "bento/ubuntu-21.04", $ubuntu_provisioning],

  [31833, "centos8-64bit",      "bento/centos-8",     $centos_provisioning],
  [31834, "centos8-64bit",      "bento/centos-8",     $centos_provisioning],
]

Vagrant.configure(2) do |config|
  config.vm.provision "shell", privileged: true, inline: 'echo "*/10 * * * * sudo /usr/sbin/ntpdate -u 0.north-america.pool.ntp.org 1.north-america.pool.ntp.org 2.north-america.pool.ntp.org 3.north-america.pool.ntp.org" | crontab -'

  config.vm.synced_folder ".", "/vagrant", disabled: true

  agents.each do |agent|
    config.vm.define "agent-#{agent[1]}-#{agent[0]}" do |node|
      node.vm.box = "#{agent[2]}"
      node.vm.network "forwarded_port", guest: 22, host: agent[0]
      node.disksize.size = "75GB"

      node.vm.provider "virtualbox" do |vb|
        vb.name = "agent-#{agent[1]}-#{agent[0]}"
        vb.memory = "4096"
        vb.cpus = "2"
      end

      node.vm.provision "shell", privileged: true, inline: agent[3]

      authorized_keys.each do |key|
        node.vm.provision "shell", inline: "echo \"#{key}\" >> /home/jenkins/.ssh/authorized_keys"
      end
    end
  end
end
