# -*- mode: ruby -*-
# vi: set ft=ruby :

authorized_keys = [
  # Jenkins controller public key
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG21+L2op3VAN+Te+X78FUIBmmHSFN61hh0TkmF2PatW jenkins@ndn-jenkins",
]

$centos_provisioning = <<~'EOF'
  # Do not disable IPv6
  sed -i -ne '/\<disable_ipv6\>/!p; $a net.ipv6.conf.all.disable_ipv6 = 0' /etc/sysctl.conf
  # Uninstall firewalld because it interferes with NFD's unit tests
  dnf -y remove firewalld
  # Upgrade everything and install what we need
  dnf -y upgrade
  dnf -y install git htop java-11-openjdk-headless nano
  # Cleanup
  dnf -y autoremove
EOF

$debian_provisioning = <<~'EOF'
  # Do not disable IPv6
  sed -i -ne '/\<disable_ipv6\>/!p; $a net.ipv6.conf.all.disable_ipv6 = 0' /etc/sysctl.conf
  # Respect the DNS servers acquired via DHCP
  sed -i -e '/dns-nameserver /d' /etc/network/interfaces
  ifdown eth0
  ifup eth0
  # Upgrade everything and install what we need
  export DEBIAN_FRONTEND=noninteractive
  apt-get -qq update
  apt-get -qy dist-upgrade
  apt-get -qy install git htop openjdk-11-jre-headless nano
  # Cleanup
  apt-get -qy autoremove
EOF

$ubuntu_provisioning = <<~'EOF'
  # Use a faster mirror
  sed -i -e 's,//\w\+\.archive\.ubuntu\.com,//mirror.arizona.edu,' /etc/apt/sources.list
  # Upgrade everything and install what we need
  export DEBIAN_FRONTEND=noninteractive
  apt-get -qq update
  apt-get -qy dist-upgrade
  apt-get -qy install git htop openjdk-11-jre-headless nano
  # Cleanup
  apt-get -qy autoremove
EOF

agents = [
  [31890, "centos9",          "generic/centos9s",     "vm1",  $centos_provisioning],
  [31891, "centos9",          "generic/centos9s",     "vm2",  $centos_provisioning],

  [31810, "debian11-i386",    "generic-x32/debian11", "vm1",  $debian_provisioning],
  [31811, "debian11-i386",    "generic-x32/debian11", "vm2",  $debian_provisioning],

  [31820, "ubuntu20.04",      "bento/ubuntu-20.04",   "vm2",  $ubuntu_provisioning],
  [31821, "ubuntu20.04",      "bento/ubuntu-20.04",   "vm1",  $ubuntu_provisioning],

  [31880, "ubuntu22.04",      "bento/ubuntu-22.04",   "vm2",  $ubuntu_provisioning],
  [31881, "ubuntu22.04",      "bento/ubuntu-22.04",   "vm1",  $ubuntu_provisioning],
  [31888, "ubuntu22.04-docs", "bento/ubuntu-22.04",   "vm2",  $ubuntu_provisioning],
]

Vagrant.configure("2") do |config|
  # Disable sharing /vagrant with the host.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  agents.each do |agent|
    # ID of the machine. Must be unique.
    vmid = "#{agent[1]}-#{agent[0]}"

    config.vm.define "agent-#{vmid}" do |node|
      node.vm.box = agent[2]
      node.vm.hostname = vmid.delete "^0-9A-Za-z-"
      node.vm.network "forwarded_port", guest: 22, host: agent[0], id: "ssh"

      node.vm.provider "virtualbox" do |vb|
        vb.name = "agent-#{vmid}"

        vb.cpus = 2
        vb.memory = 6144
        vb.default_nic_type = "virtio"

        # Disable host I/O caching.
        # https://www.virtualbox.org/manual/ch05.html#iocaching
        vb.customize "pre-boot", ["storagectl", :id, "--name", "SATA Controller", "--hostiocache", "off"]

        # Specify the folder where VirtualBox will store the machine data.
        # Warning: this is a global setting, so make sure you create one machine at a time.
        # https://www.virtualbox.org/manual/ch10.html#vboxconfigdata-machine-folder
        folder = agent[3].nil? ? "default" : File.join("", agent[3], "jenkins")
        vb.customize "pre-import", ["setproperty", "machinefolder", folder]
      end

      node.vm.provision "shell", inline: agent[4], reboot: true

      node.vm.provision "shell", inline: <<~SHELL
        useradd --create-home --shell /bin/bash jenkins
        echo 'jenkins ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/jenkins
        chmod 440 /etc/sudoers.d/jenkins

        mkdir -pv /home/jenkins/.ssh
        echo '#{authorized_keys.join("\n")}' >> /home/jenkins/.ssh/authorized_keys
        chown -cR jenkins: /home/jenkins/.ssh
        chmod -c 700 /home/jenkins/.ssh
        chmod -c 600 /home/jenkins/.ssh/authorized_keys

        cat <<EOF > /etc/ssh/sshd_config.d/auth.conf
        ChallengeResponseAuthentication no
        GSSAPIAuthentication no
        KbdInteractiveAuthentication no
        KerberosAuthentication no
        PasswordAuthentication no
        PubkeyAuthentication yes
        PermitRootLogin no
        EOF
        systemctl reload-or-restart sshd.service

        echo -e "\\U1F511 SSH host key: $(cut -d' ' -f-2 /etc/ssh/ssh_host_ed25519_key.pub)"
      SHELL
    end
  end
end
