# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.4.0"

authorized_keys = [
  # Jenkins controller public key
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG21+L2op3VAN+Te+X78FUIBmmHSFN61hh0TkmF2PatW jenkins@ndn-jenkins",
]

$centos_provisioning = <<~'EOF'
  # Do not disable IPv6
  sed -i -ne '/\<disable_ipv6\>/!p; $a net.ipv6.conf.all.disable_ipv6 = 0' /etc/sysctl.conf
  # Uninstall firewalld because it interferes with NFD's unit tests
  dnf -y remove firewalld
  # Upgrade everything and install what we need
  dnf -y upgrade
  dnf -y install git java-21-openjdk-headless
  # Cleanup
  dnf -y autoremove
EOF

$debian12_provisioning = <<~'EOF'
  # Add adoptium repo for newer jre
  cat <<EOT >/etc/apt/sources.list.d/adoptium.sources
  Types: deb
  URIs: https://packages.adoptium.net/artifactory/deb
  Suites: bookworm
  Components: main
  Signed-By:
   -----BEGIN PGP PUBLIC KEY BLOCK-----
   .
   mQENBGGTvTQBCAC6ey144n7CG8foafF6mwgIBN1fIm1ILZDuGS4tMr0/XI8pgJnT
   QvsPxZWEvtSm7bEMObzEoZJcXwjBcJl1B0ui8k5kHMTI75gCmZPsoKLFWIEpuRBQ
   PBocusw80apDmLnNDQLVQvDFtEua5gaNa/fRw9YsmBoXBqvgrjFUIdGyWoQvH5+a
   9OYlWD9n5VV0gnVMb+aclwVzB/zJw3kHGSgzuMtlAHeQiah7Y8yomQn/UIX8yqDf
   +11sP3+c87YcjkRqImRTtmKEDcEtGPAIXC6SYA+uEEkbYE0Fy0chkvtnVWJ597fa
   Epai4rnICU8zoJ6X5z3v1aM2WerhX9oq9X8PABEBAAG0QEFkb3B0aXVtIEdQRyBL
   ZXkgKERFQi9SUE0gU2lnbmluZyBLZXkpIDx0ZW11cmluLWRldkBlY2xpcHNlLm9y
   Zz6JAVIEEwEIADwWIQQ7BNdTyQUNml00PzmEPEilZfjwSwUCYZO9NAIbAwULCQgH
   AgMiAgEGFQoJCAsCBBYCAwECHgcCF4AACgkQhDxIpWX48Et4AggAjjJzYWuKV3nG
   7ngInngl8G/m9JoHr7BmwgcQXYhdy5hVkMcUx5JLeXz2LMBUH/F2nD595hgjMabk
   kVib20X8lq9RsNbdfc2hBcWU6qyHKxsIqT4boI2/XDyEzzMyyZWWNGo/27Ci7Xmj
   pWu31nh0pDdPqdyWDIKojbVVnxlCRY8as8Sm+1ufi709KCi4MuwHNsUlCSwb/fju
   NKeHkrHbLcHKUUIEcmTSKRWrpMYBzm1HYOGBz4xPuELwUfUp71ehfoyBZlp6RDRf
   l5TYI1FmCyHuvjNhrJgWv7bOTcf8yObGY+TEUhzc4xQqCrF4ur9d3opvsuPBQsv+
   Klqi5KSZgrkBDQRhk700AQgAq14okly8cFrpYVenEQPiB75AUZfKRpMduiR6IxAj
   SKcH7aSoFZ9AubUEBVpZsyT5svxoEPe1i4TdbF+m9FGy42EcOlLa3ArLTj5H8FRl
   UdGZB9I5mk4GptOzPM+aHMMu92vW/ZwjuS8DvOiQSp+cUmG1EqOMJSM7e/4BM71z
   E+OKaVJCj79pEzhG3SK/IC/OlxxyETT66NSfYJd7Sw5R6Vr19am/uNU690W0CJ+q
   VQeFpmDMr7LnfdFRIh+lJe05+PvWXeidkGjox5cbG52wf8aRIR/FgkfcFvqRMN1f
   B+dVOWueloUeVAnzcUznOKmUEs7LP9ObJhYHHgup4IAU2wARAQABiQE2BBgBCAAg
   FiEEOwTXU8kFDZpdND85hDxIpWX48EsFAmGTvTQCGwwACgkQhDxIpWX48EvXHQf/
   Q0nZsGDXnZHiBoojeSdpkO7WBjMIP3w1GdLvRpPQrS8TfOPbZuoevzCNh38Y3gwF
   yelJspvzDQrBXhgkzAGlucYg8Y7KHa5Ebm7iDgMzc37L1hYSZTYCqwd7aowfgy34
   hOk3B67LffkJpIh738Oa9CtlwxQ9xcytmBmQ1fBBOwm/9IhAwHPQuydYIs4DxWbj
   0MGSP4fDntU7e4UjsHNmhudDcYol0FaqdHHIIB9C/G4CzetRwHFOn3b4JwXMU7YU
   6aJA3mXhi3hggMC3wkT2HHZ/TquuOdNc02fypWOCDOHz0alBBJNqoVUNFNqU3tfJ
   wI4qF/KKq9BfyfucAs0ykA==
   =szki
   -----END PGP PUBLIC KEY BLOCK-----
  EOT
  # Upgrade everything and install what we need
  export DEBIAN_FRONTEND=noninteractive
  apt-get -qq update
  apt-get -qy dist-upgrade
  apt-get -qyV install git temurin-25-jre
  # Cleanup
  apt-get -qy autoremove
  apt-get -qy clean
EOF

$debian13_provisioning = <<~'EOF'
  # Upgrade everything and install what we need
  export DEBIAN_FRONTEND=noninteractive
  apt-get -qyU dist-upgrade
  apt-get -qyV install git openjdk-25-jre-headless
  # Cleanup
  apt-get -qy autoremove
  apt-get -qy clean
EOF

$ubuntu22_provisioning = <<~'EOF'
  # Do not disable IPv6
  sed -i -ne '/\<disable_ipv6\>/!p; $a net.ipv6.conf.all.disable_ipv6 = 0' /etc/sysctl.conf
  # Respect the DNS servers acquired via DHCP and disable DNSSEC
  sed -i -Ee '/nameservers:|addresses:/d' /etc/netplan/01-netcfg.yaml
  netplan apply
  sed -i -Ee 's/^DNS(SEC)?=/#&/' /etc/systemd/resolved.conf
  systemctl reload-or-restart systemd-resolved.service
  # Use a faster mirror
  sed -i -Ee 's,//mirrors\.edge\.kernel\.org,//mirror.arizona.edu,' /etc/apt/sources.list
  # Upgrade everything and install what we need
  export DEBIAN_FRONTEND=noninteractive
  apt-get -qq update
  apt-get -qy dist-upgrade
  apt-get -qyV install git openjdk-25-jre-headless
  # Cleanup
  apt-get -qy autoremove
  apt-get -qy clean
EOF

$ubuntu24_provisioning = <<~'EOF'
  # Use a faster mirror
  sed -i -Ee '/^URIs:/s,//archive\.ubuntu\.com,//mirror.arizona.edu,' /etc/apt/sources.list.d/ubuntu.sources
  # Upgrade everything and install what we need
  export DEBIAN_FRONTEND=noninteractive
  apt-get -qyU dist-upgrade
  apt-get -qyV install git openjdk-25-jre-headless
  # Cleanup
  apt-get -qy autoremove
  apt-get -qy clean
EOF

$ubuntu25_provisioning = <<~'EOF'
  # Restore sanity
  rm /etc/profile.d/pipx.sh
  # Use a faster mirror
  sed -i -Ee '/^URIs:/s,//archive\.ubuntu\.com,//mirror.arizona.edu,' /etc/apt/sources.list.d/ubuntu.sources
  # Upgrade everything and install what we need
  export DEBIAN_FRONTEND=noninteractive
  apt-get -qyU dist-upgrade
  apt-get -qyV install git openjdk-25-jre-headless
  # Cleanup
  apt-get -qy autoremove
  apt-get -qy clean
EOF

agents = [
  [31890, "centos9",          "generic/centos9s",       "vm1",  $centos_provisioning],
  [31891, "centos9",          "generic/centos9s",       "vm2",  $centos_provisioning],

  [31870, "debian12",         "bento/debian-12",        "vm1",  $debian12_provisioning],
  [31871, "debian12",         "bento/debian-12",        "vm2",  $debian12_provisioning],

  [31830, "debian13",         "bento/debian-13",        "vm1",  $debian13_provisioning],
  [31831, "debian13",         "bento/debian-13",        "vm2",  $debian13_provisioning],

  [31880, "ubuntu22.04",      "generic/ubuntu2204",     "vm2",  $ubuntu22_provisioning],
  [31881, "ubuntu22.04",      "generic/ubuntu2204",     "vm1",  $ubuntu22_provisioning],

  [31840, "ubuntu24.04",      "bento/ubuntu-24.04",     "vm2",  $ubuntu24_provisioning],
  [31841, "ubuntu24.04",      "bento/ubuntu-24.04",     "vm1",  $ubuntu24_provisioning],
  [31844, "ubuntu24.04-docs", "bento/ubuntu-24.04",     "vm1",  $ubuntu24_provisioning],

  [31850, "ubuntu25.04",      "alvistack/ubuntu-25.04", "vm2",  $ubuntu25_provisioning],
]

Vagrant.configure("2") do |config|
  # Disable sharing /vagrant with the host.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  agents.each do |agent|
    # ID of the machine. Must be unique.
    vmid = "#{agent[1]}-#{agent[0]}"

    config.vm.define "agent-#{vmid}" do |node|
      node.vm.box = agent[2]
      node.vm.box_architecture = agent[1].end_with?("-i386") ? "i386" : "amd64"
      node.vm.hostname = vmid.delete "^0-9A-Za-z-"
      node.vm.network "forwarded_port", guest: 22, host: agent[0], id: "ssh"

      node.vm.provider "virtualbox" do |vb|
        vb.name = "agent-#{vmid}"

        cpus = agent[1].end_with?("-docs") ? 2 : 3
        vb.cpus = cpus
        vb.memory = 2048 * cpus
        vb.default_nic_type = "virtio"

        # Disable host I/O caching.
        # https://www.virtualbox.org/manual/ch05.html#iocaching
        vb.customize "pre-boot", ["storagectl", :id, "--name",
                                  agent[2].start_with?("alvistack/") ? "IDE Controller" : "SATA Controller",
                                  "--hostiocache", "off"]

        # Specify the folder where VirtualBox will store the machine data.
        # Warning: this is a global setting, so make sure you create one machine at a time.
        # https://www.virtualbox.org/manual/ch10.html#vboxconfigdata-machine-folder
        folder = agent[3].nil? ? "default" : File.join("", agent[3], "jenkins")
        vb.customize "pre-import", ["setproperty", "machinefolder", folder]
      end

      node.vm.provision "shell", inline: agent[4], reboot: true

      node.vm.provision "shell", inline: <<~SHELL
        useradd --create-home --shell /bin/bash jenkins
        echo 'jenkins ALL=(ALL) NOPASSWD: ALL' >/etc/sudoers.d/jenkins
        chmod 440 /etc/sudoers.d/jenkins

        mkdir -pv /home/jenkins/.ssh
        echo '#{authorized_keys.join("\n")}' >>/home/jenkins/.ssh/authorized_keys
        chown -cR jenkins: /home/jenkins/.ssh
        chmod -c 700 /home/jenkins/.ssh
        chmod -c 600 /home/jenkins/.ssh/authorized_keys

        cat <<EOF >/etc/ssh/sshd_config.d/auth.conf
        ChallengeResponseAuthentication no
        GSSAPIAuthentication no
        KbdInteractiveAuthentication no
        KerberosAuthentication no
        PasswordAuthentication no
        PubkeyAuthentication yes
        PermitRootLogin no
        EOF
        systemctl reload-or-restart ssh.service || systemctl reload-or-restart sshd.service

        echo -e "\\U1F511 SSH host key: $(cut -d' ' -f-2 /etc/ssh/ssh_host_ed25519_key.pub)"
      SHELL
    end
  end
end
