# -*- mode: ruby -*-
# vi: set ft=ruby :

authorized_keys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG21+L2op3VAN+Te+X78FUIBmmHSFN61hh0TkmF2PatW jenkins@ndn-jenkins",
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHfJER+eGjDa0PCjN9V+VSYjMO9CiCkuTEi7w0Fio85PL/qBI67L3HmUkIFsIcA5fLiheClfeBvQPhojPpPrJSUD/3/iDgqLW/dWTQ64bpInuOCZJtZbSkVnbeVVyAxO7CF/0yh7W0NOg+IallnCimOEsDGhma686FYcvvOweCJ+w3bYA9fPwNGTBxsc++hTs/mR/WYehc1gECVZ1zE2EBNF+N9Uov+p+SuFkccpCVFM5tVzduNuQsWy6TRjoUK/q/P4BxhV8M/E2lbWK6SZ+ieOgQsC7UxBel5a6B7G//MqO4ZfHJEtpy5LuiuZMxjl/pdbfWlIwshjtnplH4BN35 jenkins@ndn-jenkins",
]

$centos_provisioning = <<~'EOF'
  dnf -y install git java-11-openjdk-headless
EOF

$debian_provisioning = <<~'EOF'
  sed -i -e '/dns-nameserver /d' /etc/network/interfaces
  ifdown eth0
  ifup eth0
  apt-get -q update
  apt-get -qy install git openjdk-11-jre-headless
EOF

$ubuntu_provisioning = <<~'EOF'
  sed -i -e 's,//\w\+\.archive\.ubuntu\.com,//mirror.arizona.edu,' /etc/apt/sources.list
  apt-get -q update
  apt-get -qy install git openjdk-11-jre-headless
EOF

agents = [
  [31890, "centos9",          "generic/centos9s",     "vm1",  $centos_provisioning],
  [31891, "centos9",          "generic/centos9s",     "vm2",  $centos_provisioning],

  [31810, "debian11-i386",    "generic-x32/debian11", "vm1",  $debian_provisioning],
  [31811, "debian11-i386",    "generic-x32/debian11", "vm2",  $debian_provisioning],

  #[31860, "ubuntu18.04",      "bento/ubuntu-18.04",   "vm1",  $ubuntu_provisioning],

  [31820, "ubuntu20.04",      "bento/ubuntu-20.04",   "vm2",  $ubuntu_provisioning],
  [31821, "ubuntu20.04",      "bento/ubuntu-20.04",   "vm1",  $ubuntu_provisioning],

  [31880, "ubuntu22.04",      "bento/ubuntu-22.04",   "vm2",  $ubuntu_provisioning],
  [31881, "ubuntu22.04",      "bento/ubuntu-22.04",   "vm1",  $ubuntu_provisioning],
  [31888, "ubuntu22.04-docs", "bento/ubuntu-22.04",   "vm2",  $ubuntu_provisioning],
]

Vagrant.configure("2") do |config|
  # Disable sharing /vagrant with the host.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  agents.each do |agent|
    # ID of the machine. Must be unique.
    vmid = "#{agent[1]}-#{agent[0]}"

    config.vm.define "agent-#{vmid}" do |node|
      node.vm.box = agent[2]
      node.vm.hostname = vmid.delete "^0-9A-Za-z-"
      node.vm.network "forwarded_port", guest: 22, host: agent[0], id: "ssh"

      node.vm.provider "virtualbox" do |vb|
        vb.name = "agent-#{vmid}"

        vb.cpus = 2
        vb.memory = 6144
        vb.default_nic_type = "virtio"

        # Disable host I/O caching.
        # https://www.virtualbox.org/manual/ch05.html#iocaching
        vb.customize "pre-boot", ["storagectl", :id, "--name", "SATA Controller", "--hostiocache", "off"]

        # Specify the folder where VirtualBox will store the machine data.
        # Warning: this is a global setting, so make sure you create one machine at a time.
        # https://www.virtualbox.org/manual/ch10.html#vboxconfigdata-machine-folder
        folder = agent[3].nil? ? "default" : File.join("", agent[3], "jenkins")
        vb.customize "pre-import", ["setproperty", "machinefolder", folder]
      end

      node.vm.provision "shell", inline: agent[4]

      node.vm.provision "shell", inline: <<~SHELL
        useradd --create-home --shell /bin/bash jenkins
        echo 'jenkins ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/jenkins
        chmod 440 /etc/sudoers.d/jenkins

        mkdir -pv /home/jenkins/.ssh
        echo '#{authorized_keys.join("\n")}' >> /home/jenkins/.ssh/authorized_keys
        chown -cR jenkins: /home/jenkins/.ssh
        chmod -c 700 /home/jenkins/.ssh
        chmod -c 600 /home/jenkins/.ssh/authorized_keys

        echo -e "\\U1F511 SSH host key: $(cut -d' ' -f-2 /etc/ssh/ssh_host_ed25519_key.pub)"
      SHELL
    end
  end
end
