# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-11"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`.
  config.vm.box_check_update = false

  # The time in seconds that Vagrant will wait for the machine to gracefully
  # halt when `vagrant halt` is called. The default is 60 seconds, but Jenkins
  # can take a long time to shut down cleanly, so we double the timeout.
  config.vm.graceful_halt_timeout = 120

  # The hostname the machine should have.
  config.vm.hostname = "ndn-jenkins"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine.
  config.vm.network "forwarded_port", guest: 22, host: 31800, id: "ssh"
  config.vm.network "forwarded_port", guest: 8080, host: 31900, id: "web"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  config.vm.provider "virtualbox" do |vb|
    # Name of the machine displayed by VirtualBox.
    vb.name = "jenkins-controller"

    vb.cpus = 2
    vb.memory = 4096
    vb.default_nic_type = "virtio"

    # Disable host I/O caching.
    # https://www.virtualbox.org/manual/ch05.html#iocaching
    vb.customize ["storagectl", :id, "--name", "SATA Controller", "--hostiocache", "off"]

    # If true, will check if guest additions are installed and up to date.
    # By default, this is true.
    # vb.check_guest_additions = false
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<~'SHELL'
    apt-get -q update
    apt-get -qy install curl default-jre-headless git
    curl -fsSL 'https://pkg.jenkins.io/debian/jenkins.io.key' > /usr/share/keyrings/jenkins.asc
    echo 'deb [signed-by=/usr/share/keyrings/jenkins.asc] https://pkg.jenkins.io/debian binary/' > /etc/apt/sources.list.d/jenkins.list
    apt-get -q update
    apt-get -qy install jenkins
  SHELL
end
